config/routes.rb
Rails.application.routes.draw do
  resources :tweets do
    resource :like
    resource :retweet
  end
  root to: "tweets#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/tweet.rb
class Tweet < ApplicationRecord
    after_create_commit { broadcast_prepend_to "tweets" }
    after_update_commit { broadcast_replace_to "tweets" }
    after_destroy_commit { broadcast_remove_to "tweets" }
  
    validates :body, presence: true
  end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
    before_action :set_tweet
  
    def create
      @tweet.increment! :likes_count
      redirect_to @tweet
    end
  
    private
  
    def set_tweet
      @tweet = Tweet.find(params[:tweet_id])
    end
  end

app/controllers/retweets_controller.rb
class RetweetsController < ApplicationController
    before_action :set_tweet
  
    def create
      @tweet.increment! :retweets_count
      redirect_to @tweet
    end
  
    private
  
    def set_tweet
      @tweet = Tweet.find(params[:tweet_id])
    end
  end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :set_tweet, only: %i[ show edit update destroy ]

  # GET /tweets or /tweets.json
  def index
    @tweets = Tweet.all
    @tweet = Tweet.new
  end

  # GET /tweets/1 or /tweets/1.json
  def show
  end

  # GET /tweets/new
  def new
    @tweet = Tweet.new
  end

  # GET /tweets/1/edit
  def edit
  end

  # POST /tweets or /tweets.json
  def create
    @tweet = Tweet.new(tweet_params)

    respond_to do |format|
      if @tweet.save
        format.html { redirect_to tweet_url(@tweet), notice: "Tweet was successfully created." }
        format.json { render :show, status: :created, location: @tweet }
      else
        format.turbo_stream { render turbo_stream: turbo_stream.replace(@tweet, partial: "tweets/form", locals: { tweet: @tweet}) }
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tweets/1 or /tweets/1.json
  def update
    respond_to do |format|
      if @tweet.update(tweet_params)
        format.html { redirect_to tweet_url(@tweet), notice: "Tweet was successfully updated." }
        format.json { render :show, status: :ok, location: @tweet }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tweets/1 or /tweets/1.json
  def destroy
    @tweet.destroy

    respond_to do |format|
      format.html { redirect_to tweets_url, notice: "Tweet was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tweet
      @tweet = Tweet.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def tweet_params
      params.require(:tweet).permit(:body, :likes_count, :retweets_count)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HotwireTest</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= yield :head %>
    <%= javascript_importmap_tags %>
    <%= turbo_include_tags %>
  </head>

  <body>
   <%= render "shared/flash_messages" %>
    <%= yield %>
  </body>
</html>

app/views/shared/_flash_messages.html.erb
<% flash.each do |name, msg| %>
  <%= content_tag :div, msg, id: "flash_#{name}" %>
<% end %>

app/views/tweets/_form.html.erb
<%= form_with(model: tweet, id: dom_id(tweet)) do |form| %>
  <% if tweet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tweet.errors.count, "error") %> prohibited this tweet from being saved:</h2>

      <ul>
        <% tweet.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/tweets/_tweet.html.erb
<%= turbo_frame_tag dom_id(tweet) do %>
  <div class="card card-body">
    <div><%= tweet.body %></div>

    <div class="mt-2">
      <%= button_to "Likes (#{tweet.likes_count})", tweet_like_path(tweet), method: :post %>
      <%= button_to "Retweets (#{tweet.retweets_count})", tweet_retweet_path(tweet), method: :post %>
      <%= link_to "Edit", edit_tweet_path(tweet) %>
    </div>
  </div>
<% end %>

app/views/tweets/edit.html.erb
<h1>Editing Tweet</h1>

<%= turbo_frame_tag dom_id(@tweet) do %>
  <div class="card card-body">
    <%= render 'form', tweet: @tweet %>
    <%= link_to "Cancel", @tweet %>
  </div>
<% end %>

app/views/tweets/index.html.erb
<p id="notice"><%= notice %></p>
<h1>Tweeter</h1>
<div class ="container">
  <%= turbo_stream_from "tweets" %>
  <%= turbo_frame_tag "tweet_form" do %>
    <%= render "tweets/form", tweet: @tweet %>
  <% end %>
  <%= turbo_frame_tag "tweets" do %>
    <%= render @tweets %>
  <% end %>
</div>

app/views/tweets/new.html.erb
<h1>New Tweet</h1>

<%= render 'form', tweet: @tweet %>
<%= link_to 'Back', tweets_path %>

app/views/tweets/show.html.erb
<p id="notice"><%= notice %></p>

<%= turbo_frame_tag dom_id(@tweet) do %>
  <%= render @tweet %>
<% end %>
<%= link_to 'Edit', edit_tweet_path(@tweet) %> |
<%= link_to 'Back', tweets_path %>